name: Rust Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: solar-screen-brightness

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@v1.4.1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Cargo Test
        run: cargo test

      - name: Cargo Format Check
        run: cargo fmt -- --check

      - name: Cargo Sort Check
        run: cargo install cargo-sort && cargo-sort --check
