name: Rust Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: solar-screen-brightness

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@v1.4.1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Install Rust Beta (we need 1.56+)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Install Ubuntu dependencies
        run: sudo apt update && sudo apt install -y libncurses-dev qtbase5-dev

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cargo Test (App)
        run: cargo test
        working-directory: ./app

      - name: Cargo Test (Installer)
        run: cargo test
        working-directory: ./installer

  check_style:
    strategy:
      matrix:
        dir: [ app, installer, windows ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cargo Format Check
        run: cargo fmt -- --check
        working-directory: ./${{ matrix.dir }}

      - name: Install Cargo Sort
        run: cargo install cargo-sort

      - name: Cargo Sort Check
        run: cargo-sort --check
        working-directory: ./${{ matrix.dir }}
